### ISSUE TITLE
Details on the parallelization

### ISSUE THREAD

**Issue by tomchor** [lesgo-jhu/lesgo#13]
I couldn't find any details on how the code is parallelized (except for maybe closed issue https://github.com/lesgo-jhu/lesgo/issues/6). I've used a version a version of the code in the past where only the `z` direction was partitioned between cores (slab decomposition), but I'm in need of a model that has better scaling (which generally codes by doing pencil decompositions).

Is there a place where I can read about these details and maybe see a scaling analysis of the code? If not, can someone briefly describe how the code is parallelized?

Thanks!

**Comment by ghanesh91** [comment]
Hi @tomchor , the details about parallelization can be found here https://lesgo.me.jhu.edu/solver.html (see MPI Domain decomposition section). 
 
Since the code is pseudo-spectral along the streamwise (x) & spanwise (y) directions and also uses the finite difference method along the wall-normal (z) direction, the code is parallel only along the z-direction (slab decomposition). We don't use pencil decomposition in our current version of the code.
